//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FineArtProject.Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FineArtProjectnewEntities : DbContext
    {
        public FineArtProjectnewEntities()
            : base("name=FineArtProjectnewEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<student> student { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<teacher> teacher { get; set; }
        public virtual DbSet<Competition> Competition { get; set; }
        public virtual DbSet<AwardsIssued> AwardsIssued { get; set; }
        public virtual DbSet<UpcommingExibition> UpcommingExibition { get; set; }
        public virtual DbSet<ArtworkStudentTable> ArtworkStudentTable { get; set; }
        public virtual DbSet<Award> Award { get; set; }
        public virtual DbSet<StaffComment> StaffComment { get; set; }
    }
}
