//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FineArtProject.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffComment
    {
        public int Id { get; set; }
        public int art_work_Id { get; set; }
        public string Mark { get; set; }
        public string comments { get; set; }
        public int staff_id { get; set; }
    
        public virtual ArtworkStudentTable ArtworkStudentTable { get; set; }
        public virtual teacher teacher { get; set; }
    }
}
